version: 2
jobs:
  build:
    working_directory: ~/workdir
    docker:
      - image: fedora:latest
    steps:
      - run:
          name: Update and install deps
          command: |
            dnf update -y
            dnf install -y \
              python36 python37 python38 \
              make gcc tox tar xz \
              libtiff-devel libjpeg-devel zlib-devel
            dnf clean all > /dev/null
      - checkout:
          path: ~/workdir/checkout
      - run:
          name: Run tox
          working_directory: ~/workdir/checkout
          command: tox
